import type { Producer, Product, Order } from '@/lib/types';

export const producers: Producer[] = [
  {
    id: 'producer-1',
    name: 'グリーン・エーカーズ・ファーム',
    location: 'カリフォルニア州ソノマ郡',
    bio: '有機栽培の伝統野菜を専門とする家族経営の農場です。私たちは持続可能な農業を信じ、地域社会に最も新鮮な農産物を提供しています。',
  },
  {
    id: 'producer-2',
    name: 'サンライズ・オーガニックス',
    location: 'ニューヨーク州ハドソンバレー',
    bio: '季節の野菜を幅広く栽培している認定有機農場です。私たちの使命は、人々を健康的でおいしい食べ物と結びつけることです。',
  },
  {
    id: 'producer-3',
    name: 'ハイドロハーベスト',
    location: 'テキサス州オースティン',
    bio: '環境への影響を最小限に抑えながら、一年中、新鮮でクリーンな葉物野菜を生産する最先端の水耕栽培農場です。',
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'レインボーチャード',
    description: '鮮やかで柔らかい葉と、マイルドで土の香りがする味わい。ソテーやサラダに最適です。',
    price: 525,
    currency: 'JPY',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'chard vegetable',
    category: '葉物野菜',
    producerId: 'producer-1',
    origin: 'カリフォルニア州ソノマ郡',
    farmingMethod: '有機栽培',
    availability: '在庫あり',
  },
  {
    id: 'prod-2',
    name: '伝統人参',
    description: '甘くて土の香りがするカラフルな人参のミックス。ローストしたり、生で楽しむのに最適です。',
    price: 600,
    currency: 'JPY',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'carrots rainbow',
    category: '根菜',
    producerId: 'producer-2',
    origin: 'ニューヨーク州ハドソンバレー',
    farmingMethod: '有機栽培',
    availability: '在庫あり',
  },
  {
    id: 'prod-3',
    name: 'バターレタス',
    description: '柔らかくバターのような葉は、どんなサラダやサンドイッチにも最適なベースになります。',
    price: 450,
    currency: 'JPY',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'lettuce fresh',
    category: '葉物野菜',
    producerId: 'producer-3',
    origin: 'テキサス州オースティン',
    farmingMethod: '水耕栽培',
    availability: '在庫あり',
  },
  {
    id: 'prod-4',
    name: 'ブロッコリーの房',
    description: '栄養豊富な新鮮でシャキシャキしたブロッコリーの房。蒸したり、ローストしたり、炒め物にするのに最適です。',
    price: 413,
    currency: 'JPY',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'broccoli fresh',
    category: 'アブラナ科',
    producerId: 'producer-1',
    origin: 'カリフォルニア州ソノマ郡',
    farmingMethod: '有機栽培',
    availability: '在庫あり',
  },
  {
    id: 'prod-5',
    name: 'ビーフステーキトマト',
    description: 'クラシックで豊かな風味を持つ、大きくてジューシーなトマト。サンドイッチやハンバーガーに最適なスライストマトです。',
    price: 675,
    currency: 'JPY',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'tomatoes vine',
    category: '果菜',
    producerId: 'producer-2',
    origin: 'ニューヨーク州ハドソンバレー',
    farmingMethod: '慣行栽培',
    availability: '在庫あり',
  },
  {
    id: 'prod-6',
    name: '赤ビーツ',
    description: '土の香りと甘さを併せ持つこのビーツは、ロースト、ピクルス、サラダに最適です。',
    price: 488,
    currency: 'JPY',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'beets fresh',
    category: '根菜',
    producerId: 'producer-1',
    origin: 'カリフォルニア州ソノマ郡',
    farmingMethod: '有機栽培',
    availability: '在庫切れ',
  },
  {
    id: 'prod-7',
    name: 'ケール',
    description: '栄養豊富で風味豊かなケール。スムージー、サラダ、ケールチップス作りに最適です。',
    price: 450,
    currency: 'JPY',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'kale green',
    category: '葉物野菜',
    producerId: 'producer-2',
    origin: 'ニューヨーク州ハドソンバレー',
    farmingMethod: '有機栽培',
    availability: '在庫あり',
  },
  {
    id: 'prod-8',
    name: 'カリフラワー',
    description: 'マイルドでナッツのような風味を持つ、用途の広い野菜。ローストしたり、マッシュしたり、「ライス」にしたりできます。',
    price: 525,
    currency: 'JPY',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'cauliflower white',
    category: 'アブラナ科',
    producerId: 'producer-3',
    origin: 'テキサス州オースティン',
    farmingMethod: '水耕栽培',
    availability: '在庫あり',
  },
];

export const orders: Order[] = [
  {
    id: 'order-1',
    date: '2023-10-26',
    items: [
      { ...products[0], quantity: 1 },
      { ...products[3], quantity: 2 },
    ],
    total: 1350,
  },
  {
    id: 'order-2',
    date: '2023-10-15',
    items: [
      { ...products[1], quantity: 1 },
      { ...products[2], quantity: 1 },
      { ...products[4], quantity: 3 },
    ],
    total: 3075,
  },
];

export const seasonalVegetables = [
  'ケール',
  'ブロッコリー',
  '人参',
  'ほうれん草',
  'ビーツ',
  'さつまいも',
  '芽キャベツ',
  '冬かぼちゃ',
  'キャベツ',
];

export const userPastPurchases = [
  'レインボーチャード',
  '伝統人参',
  'バターレタス',
  'ビーフステーキトマト',
];
