import type { Producer, Product, Order } from '@/lib/types';

export const producers: Producer[] = [
  {
    id: 'producer-1',
    name: 'Green Acres Farm',
    location: 'Sonoma County, CA',
    bio: 'A family-owned farm specializing in organic, heirloom vegetables. We believe in sustainable agriculture and providing the freshest produce to our community.',
  },
  {
    id: 'producer-2',
    name: 'Sunrise Organics',
    location: 'Hudson Valley, NY',
    bio: 'Certified organic farm growing a wide variety of seasonal vegetables. Our mission is to connect people with healthy, delicious food.',
  },
  {
    id: 'producer-3',
    name: 'HydroHarvest',
    location: 'Austin, TX',
    bio: 'State-of-the-art hydroponic farm producing crisp, clean leafy greens year-round with minimal environmental impact.',
  },
];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Rainbow Chard',
    description: 'Vibrant, tender leaves with a mild, earthy flavor. Excellent for sautéing or adding to salads.',
    price: 3.5,
    currency: 'USD',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'chard vegetable',
    category: 'Leafy Green',
    producerId: 'producer-1',
    origin: 'Sonoma County, CA',
    farmingMethod: 'Organic',
    availability: 'In Stock',
  },
  {
    id: 'prod-2',
    name: 'Heirloom Carrots',
    description: 'A colorful mix of sweet and earthy carrots, perfect for roasting or enjoying raw.',
    price: 4.0,
    currency: 'USD',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'carrots rainbow',
    category: 'Root',
    producerId: 'producer-2',
    origin: 'Hudson Valley, NY',
    farmingMethod: 'Organic',
    availability: 'In Stock',
  },
  {
    id: 'prod-3',
    name: 'Butter Lettuce',
    description: 'Soft, buttery leaves that make the perfect base for any salad or sandwich.',
    price: 3.0,
    currency: 'USD',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'lettuce fresh',
    category: 'Leafy Green',
    producerId: 'producer-3',
    origin: 'Austin, TX',
    farmingMethod: 'Hydroponic',
    availability: 'In Stock',
  },
  {
    id: 'prod-4',
    name: 'Broccoli Crowns',
    description: 'Fresh, crisp broccoli crowns packed with nutrients. Ideal for steaming, roasting, or stir-frying.',
    price: 2.75,
    currency: 'USD',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'broccoli fresh',
    category: 'Cruciferous',
    producerId: 'producer-1',
    origin: 'Sonoma County, CA',
    farmingMethod: 'Organic',
    availability: 'In Stock',
  },
  {
    id: 'prod-5',
    name: 'Beefsteak Tomatoes',
    description: 'Large, juicy tomatoes with a classic, rich flavor. The ultimate slicing tomato for sandwiches and burgers.',
    price: 4.5,
    currency: 'USD',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'tomatoes vine',
    category: 'Fruit',
    producerId: 'producer-2',
    origin: 'Hudson Valley, NY',
    farmingMethod: 'Conventional',
    availability: 'In Stock',
  },
  {
    id: 'prod-6',
    name: 'Red Beets',
    description: 'Earthy and sweet, these beets are perfect for roasting, pickling, or adding to salads.',
    price: 3.25,
    currency: 'USD',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'beets fresh',
    category: 'Root',
    producerId: 'producer-1',
    origin: 'Sonoma County, CA',
    farmingMethod: 'Organic',
    availability: 'Out of Stock',
  },
  {
    id: 'prod-7',
    name: 'Kale',
    description: 'Nutrient-dense kale with a robust flavor. Great for smoothies, salads, and making crispy kale chips.',
    price: 3.0,
    currency: 'USD',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'kale green',
    category: 'Leafy Green',
    producerId: 'producer-2',
    origin: 'Hudson Valley, NY',
    farmingMethod: 'Organic',
    availability: 'In Stock',
  },
  {
    id: 'prod-8',
    name: 'Cauliflower',
    description: 'A versatile vegetable with a mild, nutty flavor. Can be roasted, mashed, or turned into "rice".',
    price: 3.5,
    currency: 'USD',
    image: 'https://placehold.co/600x400.png',
    dataAiHint: 'cauliflower white',
    category: 'Cruciferous',
    producerId: 'producer-3',
    origin: 'Austin, TX',
    farmingMethod: 'Hydroponic',
    availability: 'In Stock',
  },
];

export const orders: Order[] = [
  {
    id: 'order-1',
    date: '2023-10-26',
    items: [
      { ...products[0], quantity: 1 },
      { ...products[3], quantity: 2 },
    ],
    total: 9.0,
  },
  {
    id: 'order-2',
    date: '2023-10-15',
    items: [
      { ...products[1], quantity: 1 },
      { ...products[2], quantity: 1 },
      { ...products[4], quantity: 3 },
    ],
    total: 20.5,
  },
];

export const seasonalVegetables = [
  'Kale',
  'Broccoli',
  'Carrots',
  'Spinach',
  'Beets',
  'Sweet Potatoes',
  'Brussels Sprouts',
  'Winter Squash',
  'Cabbage',
];

export const userPastPurchases = [
  'Rainbow Chard',
  'Heirloom Carrots',
  'Butter Lettuce',
  'Beefsteak Tomatoes',
];
